---
#
# Secret for supplying the management/edge tenant's admin credentials to the Cumulocity IoT Edge Operator.
#

apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials-secret            # Name of the secret. Same value should be supplied to "spec.adminCredentialsSecretName" field of Edge CR
  namespace: cumulocity-iot-edge			# Replace with the Edge CR name you used
type: Opaque
stringData:
  username: admin                           # Replace with admin username of the management and edge tenants
  password: Ch@nge_me_n0w    			    # Replace with the admin password
  email: admin@iot.com          		    # Replace with admin user's email