---
#
# Secret for supplying the Edge license key to the Cumulocity IoT Edge Operator.
# This secret is mandatory and its name be supplied to "spec.licenseSecretName" field of Edge CR.
#

apiVersion: v1
kind: Secret
metadata:
  name: license-secret               # Name of the secret. Same value should be supplied to "spec.licenseSecretName" field of Edge CR
  namespace: cumulocity-iot-edge     # Replace with the Edge CR name you used
type: Opaque
stringData:
  license: <EDGE-LICENSE-KEY>        # Replace with the Edge license key you received
