---
#
# Secret for supplying credentials to connect to an externally hosted Docker Registry (used to store Cumulocity microservice images)
# to the Cumulocity IoT Edge Operator.
# This secret is optional. Only required if you want this Edge deployment to use an externally hosted Docker Registry.
# Name of this secret can be supplied to "microservicesRegistry.credentialsSecretName" field of Edge CR
#

apiVersion: v1
kind: Secret
metadata:
  name: microservices-registry-credentials-secret   # Name of the secret. Same value should be supplied to "microservicesRegistry.credentialsSecretName" field of Edge CR
  namespace: cumulocity-iot-edge                    # Replace with the Edge CR name you used
type: Opaque
stringData:
  username: <REGISTRY-USERNAME>                     # Replace with externally hosted Docker Registry's username
  password: <REGISTRY-PASSWORD>                     # Replace with externally hosted Docker Registry's password