---
#
# Secret for supplying server certificate of an externally hosted Docker Registry (used to store Cumulocity microservice images)
# to the Cumulocity IoT Edge Operator.
# Name of this secret can be supplied to "microservicesRegistry.tlsSecretName" field of Edge CR
#

apiVersion: v1
kind: Secret
metadata:
  name: microservices-registry-tls-secret   # Name of the secret. Same value should be supplied to "microservicesRegistry.tlsSecretName" field of Edge CR
  namespace: cumulocity-iot-edge            # Replace with the Edge CR name you used
type: Opaque
stringData:
  certificate: <REGISTRY-CERTIFICATE>       # Replace with externally hosted Docker Registry's server certificate
