---
#
# Secret for supplying the Software AG Registry (registry.c8y.io) credentials to the Cumulocity IoT Edge Operator.
# Name of this secret is fixed "sag-registry-credentials"
#

apiVersion: v1
kind: Secret
metadata:
  name: sag-registry-credentials          # Name of this secret should not change.
  namespace: cumulocity-iot-edge          # Replace with the Edge CR name you used
type: Opaque
stringData:
  username: <EDGE-REPO-USERNAME>          # Edge Repo username you received
  password: <EDGE-REPO-PASSWORD>          # Edge Repo password you received