---
#
# Secret for supplying the TLS Key/Certificates to the Cumulocity IoT Edge Operator.
# This secret is optional. If not provided the Operator will generate self signed certificates.
#

apiVersion: v1
kind: Secret
metadata:
  name: tls-secret                        # Name of the secret. Same value should be supplied to "spec.tlsSecretName" field of Edge CR
  namespace: cumulocity-iot-edge          # Replace with the Edge CR name you used
type: Opaque
stringData:
  key: <PRIVATE-KEY>                      # Replace with the private key for the domain
  certificateChain: <CERTIFICATE-CHAIN>   # Replace with the certificate chain of the private key for the domain
