---
#
# Ingress to access Cumulocity IoT application running on Pods labeled "cumulocity-core" over HTTP.
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cumulocity-iot-edge
  name: cumulocity-iot-edge-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cumulocity-iot-edge-http           # Name of the HTTP service for exposing the "cumulocity-core" pods
                port:
                  number: 80