---
#
# Ingress to access Cumulocity IoT application running on Pods labeled "cumulocity-core" over HTTP.
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cumulocity-iot-edge                # Replace with the Edge CR name you used
  name: http-ingress-traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "false"  # As SSL termination happens at OpenResty running in the core pod
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cumulocity-iot-edge-service-http     # Replace 'cumulocity-iot-edge' with the Edge CR name you used. Name of the HTTP service for exposing the "cumulocity-core" pods
                port:
                  number: 80