apiVersion: v1
kind: Service
metadata:
  labels:
    app: cumulocity-iot-edge
  name: cumulocity-iot-edge-http
  namespace: cumulocity-iot-edge
spec:
  ports:
    - name: 443-443
      port: 443
      targetPort: 443
    - name: 80-80
      port: 80
      targetPort: 80
  selector:
    app: cumulocity-iot-edge
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cumulocity-iot-edge
  name: cumulocity-iot-edge-mqtt
  namespace: cumulocity-iot-edge
spec:
  ports:
    - name: 1884-1884
      port: 1884
      targetPort: 1884
    - name: 1883-1883
      port: 1883
      targetPort: 1883
  selector:
    app: cumulocity-iot-edge
  type: LoadBalancer